### PR TITLE
Don't error in git_commit_all(), polish docs

### LINKED ISSUE #42: Need to clarify what git_commit_all() does about new (untracked) files
Currently `git_commit_all()` does not address new, untracked files.

``` r
library(gert)
#> Linking to libgit2 v0.28.4, ssh support: YES
#> Global config: /Users/jenny/.gitconfig
#> Default user: Jenny Bryan <jenny.f.bryan@gmail.com>

r <- tempfile(pattern = "gert")
git_init(r)
#> [1] "/private/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T/RtmpZKRbiJ/gert97c33bf58c92/"

writeLines(letters[1:6], file.path(r, "alphabet.txt"))
git_status(repo = r)
#> # A tibble: 1 x 3
#>   file         status staged
#> * <chr>        <chr>  <lgl> 
#> 1 alphabet.txt new    FALSE

# git_commit_all() does not work when there's only new files
git_commit_all("nope", repo = r)
#> Error in git_commit(message = message, author = author, committer = committer, : No staged files to commit. Run git_add() to select files.

git_add("alphabet.txt", repo = r)
#> <git repository>: /private/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T/RtmpZKRbiJ/gert97c33bf58c92[@NA]
git_commit("Start alphabet file", repo = r)
#> [1] "7ed57f6c53dfc2cba40ea2573fe540d1f5a01262"
git_status(repo = r)
#> # A tibble: 0 x 3
#> # … with 3 variables: file <chr>, status <chr>, staged <lgl>

writeLines(month.name[1:6], file.path(r, "months.txt"))
git_status(repo = r)
#> # A tibble: 1 x 3
#>   file       status staged
#> * <chr>      <chr>  <lgl> 
#> 1 months.txt new    FALSE

# git_commit_all() does not work when there's only new files
# second demo, to prove this has nothing to do with an unborn branch or whatever
git_commit_all("nope", repo = r)
#> Error in git_commit(message = message, author = author, committer = committer, : No staged files to commit. Run git_add() to select files.

cat(letters[7:9], file = file.path(r, "alphabet.txt"), sep = "\n", append = TRUE)
git_status(repo = r)
#> # A tibble: 2 x 3
#>   file         status   staged
#> * <chr>        <chr>    <lgl> 
#> 1 alphabet.txt modified FALSE 
#> 2 months.txt   new      FALSE

# this picks up only the modification to the tracked file
git_commit_all("Add more letters", repo = r)
#> [1] "27f0f048fcd0a4358b239dc52d7fdc72bd07931f"

# the new file is still there, unstaged, untracked
git_status(repo = r)
#> # A tibble: 1 x 3
#>   file       status staged
#> * <chr>      <chr>  <lgl> 
#> 1 months.txt new    FALSE

# cleanup
unlink(r, recursive = TRUE)
```

<sup>Created on 2020-06-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I suppose `git_commit_all()` is intended to emulate `git add -A && git commit -m "Your Message"` which *would* add new, untracked files?

@jeroen What do you want this function to do?

If current behaviour is intended, we should change the docs and maybe messaging.

Or we should change the behaviour to match `git add -A && git commit -m "Your Message"` and add & commit new, untracked, unignored files.

### PR DESCRIPTION
**Pull request by jennybc**
Closes #42 

Still WIP

### CODE REVIEW

File: R/commit.R [hunk 1]
```diff
@@ -1,22 +1,26 @@
 #' Stage and commit changes
 #'
-#' @description To commit changes, start with *staging* the files to be included
-#' in the commit using [git_add()] or [git_rm()]. Use [git_status()] to see an
-#' overview of staged and unstaged changes, and finally [git_commit()] creates
-#' a new commit with currently staged files.
+#' @description
+#' To commit changes, start by *staging* the files to be included in the commit
+#' using `git_add()` or `git_rm()`. Use `git_status()` to see an overview of
```
Comment (jennybc) [inline R/commit.R:5]: Here and elsewhere I did the usual un-linking of function names that are actually documented in this topic, i.e. replaced square brackets with backticks.

File: R/commit.R [hunk 2]
```diff
@@ -1,22 +1,26 @@
...
+#' staged and unstaged changes, and finally `git_commit()` creates a new commit
+#' with currently staged files.
 #'
-#' [git_commit_all] is a shorthand that will automatically stage all new and
```
Comment (jennybc) [inline R/commit.R:8]: I've removed the misleading "automatically stage all new and modified" and been explicit about how new files are (not) handled.

File: R/commit.R [hunk 3]
```diff
@@ -70,14 +74,25 @@ git_commit <- function(message, author = NULL, committer = NULL, repo = '.'){
...
-  deleted <- stat$file[!stat$staged & stat$status == "deleted"]
+
+  deleted <- unstaged$file[unstaged$status == "deleted"]
   if(length(deleted))
     git_rm(deleted, repo = repo)
-  git_commit(message = message, author = author, committer = committer, repo = repo)
+
+  new_files <- unstaged$file[unstaged$status == "new"]
+  if (length(new_files)) {
+    message("New, untracked files found, which won't be committed. Use git_add() instead.")
```
Comment (jennybc) [inline R/commit.R]: This is new. It feels a little asymmetric to message about this but to not say anything about our other actions. But for a magic function like this, maybe messaging  is appropriate? Maybe the other branches should message. It feels like people should be forced/invited to educate themselves about what `git_commit_all()` has done.

File: R/commit.R [hunk 4]
```diff
@@ -70,14 +74,25 @@ git_commit <- function(message, author = NULL, committer = NULL, repo = '.'){
...
+  }
+
+  staged <- subset(git_status(repo), subset = staged)
+  if (nrow(staged)) {
```
Comment (jennybc) [inline R/commit.R]: New behaviour. We no longer error if there's nothing to be done. We just quietly do nothing. Again, this feels appropriate here, because the user has not, after all, requested any specific action.

**Comment by jennybc** [comment]
@jeroen I can finish this off once you indicate your opinion on a few things.

**Comment by jeroen** [comment]
Thanks for the doc updates.

I would prefer this function behavior to match the command line. In my view `git_commit_all` isn't really magical, `git commit -a -m` is a common way to commit changes. I use it myself a lot. 

It's a sensible default by the command line to not automatically add all untracked files because you would end up accidentally committing all temporary files that are floating around in the directory; that is rarely desired. 

I'm not sure if it is helpful to give a generic message about this every time the function is used. The command line doesn't do this it think it quickly gets annoying. Perhaps it could be made helpful if the message lists the untracked files, that way at least it contains some valuable information.

**Comment by jennybc** [comment]
What about:

If `git_commit_all()` is not going to do anything, we message instead of error.

I'm just thinking in downstream programmatic use, you could want to call this in places where it's possible there is nothing to be done. In your interactive use, the error is fine. But in client packages, it means people have to do a pre-analysis or use `tryCatch()`.

**Comment by jeroen** [comment]
> If git_commit_all() is not going to do anything, we message instead of error.

Actually I think it should error, especially in a scripted setting. The script may be making important changes and then subsequently calling `git_commit_all("commit important changes")` to create a new commit that stores those things. 

If there are no changes, that probably means something has gone wrong. At least it wasn't able to create the new `"made the required changes"` commit, so it makes sense to error. I'd like to stay close here to the command line behavior, which also returns non-success for `git commit -a -m` if there is nothing to commit.

I think the use cases that both of us have in mind are a bit different here. We could add a separate function that is more what you had in mind like "if any files are new or changed, commit now."

**Comment by jeroen** [comment]
I've merged the updates for the docs, but kept the old behavior for above reasons. I really want it to mimic as close as possible `git commit -a -m` because I use that every day.

It think would be useful to expose a separate function that covers the use-case that you have in mind, which sounds more like "save all".
